/*____________________________________   REMOVER SEQUENCIAS   ____________________________________*/

DROP SEQUENCE mensagens_id; 
DROP SEQUENCE produtos_id;
DROP SEQUENCE trocas_id;
DROP SEQUENCE fotos_id;
DROP SEQUENCE propostas_id;

/*____________________________________   CRIAR SEQUENCIAS   ____________________________________*/

CREATE SEQUENCE  mensagens_id  MINVALUE 0 INCREMENT BY 1 START WITH 0 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  produtos_id  MINVALUE 0 INCREMENT BY 1 START WITH 0 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  trocas_id  MINVALUE 0 INCREMENT BY 1 START WITH 0 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  fotos_id  MINVALUE 0 INCREMENT BY 1 START WITH 0 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  propostas_id  MINVALUE 0 INCREMENT BY 1 START WITH 0 CACHE 20 NOORDER  NOCYCLE ;
